/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#include "stm32f407xx.h"
#include "sched.h"
//#include "stm32f407xx_Mcu.h"
//#include "Lcd.h"
#include "ModeManagement.h"
#include "EventManagement.h"

#include "stm32f407xx_gpio_driver.h"
#include "stm32f407xx_timer_driver.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void delay()
{
	for(uint32_t i = 0; i < 5000000/4; i++);
}

uint8_t delay_done = 0 ;

int main(void)
{


	printf("I am legend\n");
	GPIO_Handle_t GopiLed;
	GopiLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GopiLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GopiLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GopiLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GopiLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GopiLed.pGPIOx = GPIOD;

	GPIO_PeriClockControl(GPIOD, ENABLE);
	GPIO_Init(&GopiLed);

    //MCU_Init;
	//Timer init
	//timer2_init();

    //EventMngt_Init();
    //Lcd_Driver_Init();

    //scheduler_loop();
    /* Loop forever */
	for(;;)
	{
		if(GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0) == 1)
		{
		    // Start a 500ms delay
		    timer2_delay_ms(500);
			while(delay_done == 0);
		    delay_done = 0;
			GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
		}
	}
}




